Repository nunit/nunit-console, pull requests merged in 2018-08, with the labels that each got.

#447 Output CI version info to console
  build.cake
  ci.cake
  src/CommonAssemblyInfo.cs
  src/NUnitConsole/ConsoleVersion.cs
  src/NUnitConsole/nunit3-console/Program.cs
  src/NUnitEngine/EngineApiVersion.cs
  src/NUnitEngine/EngineVersion.cs
  src/NUnitEngine/notest-assembly/Properties/AssemblyInfo.cs
Labels: awaiting:review

#435 Fix timeout of agent-discovery due to CPU starvation
  src/NUnitEngine/nunit-agent/AgentExitCodes.cs
  src/NUnitEngine/nunit-agent/Program.cs
  src/NUnitEngine/nunit.engine.tests/Runners/MultipleTestProcessRunnerTests.cs
  src/NUnitEngine/nunit.engine/Runners/MultipleTestProcessRunner.cs
  src/NUnitEngine/nunit.engine/Services/TestAgency.cs
Labels: awaiting:review

#448 Update vs-project-loader extension to 3.8.0
  .gitignore
  choco/nunit-console-with-extensions.nuspec
  nuget/runners/nunit.console-runner-with-extensions.nuspec
  nuget/runners/nunit.runners.nuspec
Labels: blocked

#455 Remove CF, Silverlight and PORTABLE functionality
  src/CommonAssemblyInfo.cs
  src/NUnitConsole/nunit3-console.tests/DefaultOptionsProviderTests.cs
  src/NUnitConsole/nunit3-console.tests/OutputSpecificationTests.cs
  src/NUnitConsole/nunit3-console/Options.cs
  src/NUnitEngine/nunit.engine.tests/RuntimeFrameworkTests.cs
  src/NUnitEngine/nunit.engine/RuntimeFramework.cs
  src/NUnitEngine/nunit.engine/RuntimeType.cs
Labels: is:refactor

#452 Multi-Targeting of engine extensions (.NET Framework only)
  src/NUnitConsole/nunit3-console/ConsoleRunner.cs
  src/NUnitEngine/nunit.engine.api/Extensibility/IExtensionNode.cs
  src/NUnitEngine/nunit.engine.tests/Extensibility/ExtensionAssemblyTests.cs
  src/NUnitEngine/nunit.engine.tests/Extensibility/ExtensionSelectorTests.cs
  src/NUnitEngine/nunit.engine.tests/RuntimeFrameworkTests.cs
  src/NUnitEngine/nunit.engine.tests/Services/ExtensionAssemblyTests.cs
  src/NUnitEngine/nunit.engine/Extensibility/ExtensionAssembly.cs
  src/NUnitEngine/nunit.engine/Extensibility/ExtensionNode.cs
  src/NUnitEngine/nunit.engine/Extensibility/ExtensionSelector.cs
  src/NUnitEngine/nunit.engine/Extensibility/IExtensionAssembly.cs
  src/NUnitEngine/nunit.engine/Internal/TargetFrameworkHelper.cs
  src/NUnitEngine/nunit.engine/Properties/AssemblyInfo.cs
  src/NUnitEngine/nunit.engine/RuntimeFramework.cs
  src/NUnitEngine/nunit.engine/Services/ExtensionAssembly.cs
  src/NUnitEngine/nunit.engine/Services/ExtensionService.cs
Labels: awaiting:review
