Repository nunit/nunit-console, pull requests merged in 2019-04, with the labels that each got.

#611 Set DisableImplicitNuGetFallbackFolder and bump Ubuntu on Travis
  .travis.yml
  appveyor.yml
  src/NUnitConsole/nunit3-console.tests/nunit3-console.tests.csproj
  src/NUnitConsole/nunit3-console/nunit3-console.csproj
  src/NUnitEngine/notest-assembly/notest-assembly.csproj
  src/NUnitEngine/nunit-agent/nunit-agent-x86.csproj
  src/NUnitEngine/nunit-agent/nunit-agent.csproj
  src/NUnitEngine/nunit.engine.api/nunit.engine.api.csproj
  src/NUnitEngine/nunit.engine.tests/nunit.engine.tests.csproj
  src/NUnitEngine/nunit.engine/nunit.engine.csproj
Labels: awaiting:review, is:build

#613 Fix agent crash when WorkDirectory path terminates in slash
  src/NUnitEngine/nunit-agent/Program.cs
  src/NUnitEngine/nunit.engine.tests/Internal/ProcessUtilsTests.cs
  src/NUnitEngine/nunit.engine/Internal/ProcessUtils.cs
  src/NUnitEngine/nunit.engine/Services/TestAgency.cs
Labels: awaiting:review

#597 Add RunnerSelectionTests for 'single project' package
  NUnitConsole.sln.DotSettings
  src/NUnitEngine/nunit.engine.api/TestPackage.cs
  src/NUnitEngine/nunit.engine.tests/Services/TestRunnerFactoryTests/Results/Net20SingleProjectExpectedRunnerResults.cs
  src/NUnitEngine/nunit.engine.tests/Services/TestRunnerFactoryTests/RunnerSelectionTests.cs
  src/NUnitEngine/nunit.engine.tests/Services/TestRunnerFactoryTests/TestCases/Net20ProjectTestCases.cs
  src/NUnitEngine/nunit.engine.tests/Services/TestRunnerFactoryTests/TestCases/NetStandardTestCases.cs
  src/NUnitEngine/nunit.engine.tests/Services/TestRunnerFactoryTests/TestPackageFactory.cs
  src/NUnitEngine/nunit.engine/Runners/ProcessRunner.cs
Labels: awaiting:review

#612 Fix logging when including exception
  src/NUnitConsole/nunit3-console.tests/ExceptionHelperTests.cs
  src/NUnitConsole/nunit3-console/ConsoleRunner.cs
  src/NUnitConsole/nunit3-console/Program.cs
  src/NUnitEngine/nunit-agent/Program.cs
  src/NUnitEngine/nunit-agent/nunit-agent-x86.csproj
  src/NUnitEngine/nunit-agent/nunit-agent.csproj
  src/NUnitEngine/nunit.engine.api/ILogger.cs
  src/NUnitEngine/nunit.engine/Agents/RemoteTestAgent.cs
  src/NUnitEngine/nunit.engine/Internal/DomainDetailsBuilder.cs
  src/NUnitEngine/nunit.engine/Internal/ExceptionHelper.cs
  src/NUnitEngine/nunit.engine/Internal/Logging/Logger.cs
  src/NUnitEngine/nunit.engine/Internal/TcpChannelUtils.cs
  src/NUnitEngine/nunit.engine/Runners/ProcessRunner.cs
Labels: awaiting:review, is:bug, pri:normal

#599 Add RunnerSelectionTests for 'multiple project' packages
  src/NUnitEngine/nunit.engine.tests/Services/DefaultTestRunnerFactoryTests.cs
  src/NUnitEngine/nunit.engine.tests/Services/TestRunnerFactoryTests/Results/Net20TwoProjectAssemblyExpectedRunnerResults.cs
  src/NUnitEngine/nunit.engine.tests/Services/TestRunnerFactoryTests/TestCases/Net20ProjectTestCases.cs
  src/NUnitEngine/nunit.engine.tests/Services/TestRunnerFactoryTests/TestCases/NetStandardTestCases.cs
  src/NUnitEngine/nunit.engine.tests/Services/TestRunnerFactoryTests/TestPackageFactory.cs
Labels: awaiting:review

#614 RunnerSelectionTest layout changes
  src/NUnitEngine/nunit.engine.tests/Services/TestRunnerFactoryTests/Results/Net20SingleAssemblyExpectedRunnerResults.cs
  src/NUnitEngine/nunit.engine.tests/Services/TestRunnerFactoryTests/Results/Net20TwoAssemblyExpectedRunnerResults.cs
Labels: awaiting:review
