Repository nunit/nunit-console, pull requests merged in 2019-05, with the labels that each got.

#618 Test double-negative filters
  src/NUnitEngine/nunit.engine.tests/Services/TestFilteringTests.cs
  src/NUnitEngine/nunit.engine.tests/Services/TestSelectionParserTests.cs
Labels: awaiting:review

#616 Complete Runner Selection Tests
  src/NUnitEngine/nunit.engine.tests/Runners/MasterTestRunnerTests.cs
  src/NUnitEngine/nunit.engine.tests/Services/DefaultTestRunnerFactoryTests.cs
  src/NUnitEngine/nunit.engine.tests/Services/TestRunnerFactoryTests/Results/Net20OneAssemblyOneProjectExpectedRunnerResults.cs
  src/NUnitEngine/nunit.engine.tests/Services/TestRunnerFactoryTests/Results/Net20SingleAssemblyListCtorExpectedRunnerResults.cs
  src/NUnitEngine/nunit.engine.tests/Services/TestRunnerFactoryTests/Results/Net20SingleAssemblyStringCtorExpectedRunnerResults.cs
  src/NUnitEngine/nunit.engine.tests/Services/TestRunnerFactoryTests/Results/Net20SingleProjectListCtorExpectedRunnerResults.cs
  src/NUnitEngine/nunit.engine.tests/Services/TestRunnerFactoryTests/Results/Net20SingleProjectStringCtorExpectedRunnerResults.cs
  src/NUnitEngine/nunit.engine.tests/Services/TestRunnerFactoryTests/Results/Net20ThreeItemExpectedRunnerResults.cs
  src/NUnitEngine/nunit.engine.tests/Services/TestRunnerFactoryTests/Results/Net20TwoProjectExpectedRunnerResults.cs
  src/NUnitEngine/nunit.engine.tests/Services/TestRunnerFactoryTests/RunnerSelectionTests.cs
  src/NUnitEngine/nunit.engine.tests/Services/TestRunnerFactoryTests/TestCases/Net20AssemblyTestCases.cs
  src/NUnitEngine/nunit.engine.tests/Services/TestRunnerFactoryTests/TestCases/Net20MixedProjectAndAssemblyTestCases.cs
  src/NUnitEngine/nunit.engine.tests/Services/TestRunnerFactoryTests/TestCases/Net20ProjectTestCases.cs
  src/NUnitEngine/nunit.engine.tests/Services/TestRunnerFactoryTests/TestCases/NetStandardTestCases.cs
  src/NUnitEngine/nunit.engine.tests/Services/TestRunnerFactoryTests/TestPackageFactory.cs
Labels: awaiting:review

#623 Add comment explaining use of TestPackage IDs
  src/NUnitEngine/nunit.engine.api/TestPackage.cs
Labels: awaiting:review

#600 Change XmlTransform encoding to UTF-8
  src/NUnitEngine/nunit.engine/Services/ResultWriters/XmlTransformResultWriter.cs
Labels: awaiting:contributor

#634 Remove unnecessary stream creation in XML Transform writer
  src/NUnitEngine/nunit.engine/Services/ResultWriters/XmlTransformResultWriter.cs
Labels: awaiting:review

#622 Delay Creation of test engine runner and package expansion till actually needed
  src/NUnitEngine/nunit.engine.tests/Services/Fakes/FakeRuntimeService.cs
  src/NUnitEngine/nunit.engine.tests/Services/InProcessTestRunnerFactoryTests.cs
  src/NUnitEngine/nunit.engine.tests/Services/TestRunnerFactoryTests/Results/Net20OneAssemblyOneProjectExpectedRunnerResults.cs
  src/NUnitEngine/nunit.engine.tests/Services/TestRunnerFactoryTests/Results/Net20SingleAssemblyListCtorExpectedRunnerResults.cs
  src/NUnitEngine/nunit.engine.tests/Services/TestRunnerFactoryTests/Results/Net20SingleAssemblyStringCtorExpectedRunnerResults.cs
  src/NUnitEngine/nunit.engine.tests/Services/TestRunnerFactoryTests/Results/Net20SingleProjectListCtorExpectedRunnerResults.cs
  src/NUnitEngine/nunit.engine.tests/Services/TestRunnerFactoryTests/Results/Net20SingleProjectStringCtorExpectedRunnerResults.cs
  src/NUnitEngine/nunit.engine.tests/Services/TestRunnerFactoryTests/Results/Net20ThreeItemExpectedRunnerResults.cs
  src/NUnitEngine/nunit.engine.tests/Services/TestRunnerFactoryTests/Results/Net20TwoProjectExpectedRunnerResults.cs
  src/NUnitEngine/nunit.engine.tests/Services/TestRunnerFactoryTests/RunnerResult.cs
  src/NUnitEngine/nunit.engine.tests/Services/TestRunnerFactoryTests/RunnerSelectionTests.cs
  src/NUnitEngine/nunit.engine.tests/Services/TestRunnerFactoryTests/TestCases/NetStandardTestCases.cs
  src/NUnitEngine/nunit.engine/Runners/MasterTestRunner.cs
  src/NUnitEngine/nunit.engine/Services/DefaultTestRunnerFactory.cs
  src/NUnitEngine/nunit.engine/Services/InProcessTestRunnerFactory.cs
Labels: awaiting:discussion, awaiting:review

#630 add label option "BeforeAndAfter"
  src/NUnitConsole/nunit3-console.tests/TestEventHandlerTests.cs
  src/NUnitConsole/nunit3-console/CommandLineOptions.cs
  src/NUnitConsole/nunit3-console/TestEventHandler.cs
Labels: awaiting:discussion, awaiting:review

#637 Refactor RunnerSelectionTests
  src/NUnitEngine/nunit.engine.tests/Services/TestRunnerFactoryTests/Results/Net20OneAssemblyOneProjectExpectedRunnerResults.cs
  src/NUnitEngine/nunit.engine.tests/Services/TestRunnerFactoryTests/Results/Net20SingleAssemblyListCtorExpectedRunnerResults.cs
  src/NUnitEngine/nunit.engine.tests/Services/TestRunnerFactoryTests/Results/Net20SingleAssemblyStringCtorExpectedRunnerResults.cs
  src/NUnitEngine/nunit.engine.tests/Services/TestRunnerFactoryTests/Results/Net20SingleProjectListCtorExpectedRunnerResults.cs
  src/NUnitEngine/nunit.engine.tests/Services/TestRunnerFactoryTests/Results/Net20SingleProjectStringCtorExpectedRunnerResults.cs
  src/NUnitEngine/nunit.engine.tests/Services/TestRunnerFactoryTests/Results/Net20ThreeItemExpectedRunnerResults.cs
  src/NUnitEngine/nunit.engine.tests/Services/TestRunnerFactoryTests/Results/Net20TwoAssemblyExpectedRunnerResults.cs
  src/NUnitEngine/nunit.engine.tests/Services/TestRunnerFactoryTests/Results/Net20TwoProjectExpectedRunnerResults.cs
  src/NUnitEngine/nunit.engine.tests/Services/TestRunnerFactoryTests/RunnerResult.cs
  src/NUnitEngine/nunit.engine.tests/Services/TestRunnerFactoryTests/TestCases/NetStandardTestCases.cs
Labels: awaiting:review, is:enhancement
