Repository nunit/nunit-console, pull requests merged in 2019-01, with the labels that each got.

#525 Separate NuGet Restore for Appveyor build
  appveyor.yml
Labels: is:build

#527 Correct label for issues for new contributors
  CONTRIBUTING.md
Labels: awaiting:review, is:docs

#516 Initial Test Runner Selection Tests (1/4)
  src/NUnitEngine/nunit.engine.tests/Services/TestRunnerFactoryTests/Net20AssemblyTestCases.cs
  src/NUnitEngine/nunit.engine.tests/Services/TestRunnerFactoryTests/NetStandardAssemblyTestCases.cs
  src/NUnitEngine/nunit.engine.tests/Services/TestRunnerFactoryTests/RunnerResult.cs
  src/NUnitEngine/nunit.engine.tests/Services/TestRunnerFactoryTests/RunnerResultComparer.cs
  src/NUnitEngine/nunit.engine.tests/Services/TestRunnerFactoryTests/RunnerSelectionTests.cs
Labels: awaiting:review

#526 Ensure Load and Reload incorporate test-run and prevent exception
  src/NUnitEngine/nunit.engine.tests/Runners/MasterTestRunnerTests.cs
  src/NUnitEngine/nunit.engine/Runners/MasterTestRunner.cs
Labels: awaiting:review

#520 Runner selection tests (2/4) - Add Process/Domain model tests
  src/NUnitEngine/nunit.engine.tests/Services/TestRunnerFactoryTests/NetStandardAssemblyTestCases.cs
  src/NUnitEngine/nunit.engine.tests/Services/TestRunnerFactoryTests/Results/Net20SingleAssemblyExpectedRunnerResults.cs
  src/NUnitEngine/nunit.engine.tests/Services/TestRunnerFactoryTests/Results/Net20TwoAssemblyExpectedRunnerResults.cs
  src/NUnitEngine/nunit.engine.tests/Services/TestRunnerFactoryTests/RunnerResult.cs
  src/NUnitEngine/nunit.engine.tests/Services/TestRunnerFactoryTests/RunnerSelectionTests.cs
  src/NUnitEngine/nunit.engine.tests/Services/TestRunnerFactoryTests/TestCases/Net20AssemblyTestCases.cs
  src/NUnitEngine/nunit.engine.tests/Services/TestRunnerFactoryTests/TestCases/NetStandardAssemblyTestCases.cs
  src/NUnitEngine/nunit.engine.tests/Services/TestRunnerFactoryTests/TestPackageFactory.cs
Labels: awaiting:review
