Repository nunit/nunit-console, pull requests merged in 2019-08, with the labels that each got.

#671 Manually updated .NET Core SDK on Linux build
  azure-pipelines.yml
Labels: awaiting:review, is:build, pri:high

#670 Fix for running multiple test packages targetting different frameworks on the correct platform
  src/NUnitEngine/nunit.engine.api/IRuntimeFrameworkService.cs
  src/NUnitEngine/nunit.engine.tests/Services/RuntimeFrameworkServiceTests.cs
  src/NUnitEngine/nunit.engine/Services/RuntimeFrameworkService.cs
Labels: awaiting:review

#669 nunit.console-runner-with-extensions.nuspec: Remove outdated release notes
  nuget/runners/nunit.console-runner-with-extensions.nuspec
Labels: awaiting:team
