Repository nunit/nunit-console, pull requests merged in 2019-03, with the labels that each got.

#559 Specify productVersion as an argument
  build.cake
Labels: awaiting:review

#558 Add deprecated nunit.engine.netstandard nuspec
  NUnitConsole.sln
  build.cake
  nuget/deprecated/nunit.engine.netstandard.nuspec
  nuget/deprecated/nunit.runners.nuspec
Labels: awaiting:review

#560 Comments documenting purpose of various runners
  src/NUnitEngine/nunit.engine/Runners/AbstractTestRunner.cs
  src/NUnitEngine/nunit.engine/Runners/AggregatingTestRunner.cs
  src/NUnitEngine/nunit.engine/Runners/DirectTestRunner.cs
  src/NUnitEngine/nunit.engine/Runners/MasterTestRunner.cs
  src/NUnitEngine/nunit.engine/Runners/ProcessRunner.cs
Labels: awaiting:review

#557 Disable CliFallbackFolder as a nuget source
  src/NUnitEngine/mock-assembly/mock-assembly.csproj
Labels: awaiting:review

#555 Use ExtendedTextWriter in TestEventHandler
  src/NUnitConsole/nunit3-console.tests/TestEventHandlerTests.cs
  src/NUnitConsole/nunit3-console/ConsoleRunner.cs
  src/NUnitConsole/nunit3-console/TestEventHandler.cs
Labels: awaiting:review, blocked

#549 Ensure that all subpackages are located correctly
  src/NUnitEngine/nunit.engine/Internal/TestPackageExtensions.cs
  src/NUnitEngine/nunit.engine/Runners/AggregatingTestRunner.cs
  src/NUnitEngine/nunit.engine/Runners/DirectTestRunner.cs
Labels: awaiting:review

#565 Eliminate -dbg suffix from version
  build.cake
Labels: awaiting:review

#568 Removed unnecessary CanLoadFrom invocation
  src/NUnitEngine/nunit.engine/Runners/MasterTestRunner.cs
Labels: awaiting:review

#553 Don't try to load extensions in case of incompatible target frameworks (fix #524)
  src/NUnitEngine/nunit.engine.tests/Services/ExtensionServiceTests.cs
  src/NUnitEngine/nunit.engine/Services/ExtensionService.cs
Labels: awaiting:review

#579 Resolve MSBuild when only 16.0 or only a preview of VS is installed
  build.cake
Labels: is:build

#573 Single YAML-based Azure DevOps build
  .editorconfig
  azure-pipelines.yml
  build.cake
  tools/packages.config
Labels: awaiting:review

#585 Pass whitespace in work directory path to agents correctly (Based on #572)
  src/NUnitEngine/nunit.engine/Services/TestAgency.cs
Labels: awaiting:review

#572 Fixed support for space characters in the work directory path
  src/NUnitEngine/nunit.engine/Services/TestAgency.cs
Labels: awaiting:contributor

#587 Disable new MSBuild GenerateSupportedRuntime functionality, which breaks framework targetting
  src/NUnitEngine/nunit-agent/nunit-agent-x86.csproj
  src/NUnitEngine/nunit-agent/nunit-agent.csproj
Labels: awaiting:review, pri:high

#575 Add --testparam to enable test parameters to contain semicolons
  src/NUnitConsole/nunit3-console.tests/CommandLineTests.cs
  src/NUnitConsole/nunit3-console/CommandLineOptions.cs
  src/NUnitConsole/nunit3-console/Program.cs
Labels: awaiting:review
