Repository nunit/nunit-console, pull requests merged in 2020-05, with the labels that each got.

#741 Create NET40 agent and eliminate use of COMPLUS_Version variable
  NUnitConsole.sln
  build.cake
  choco/nunit.agent.addins
  msi/nunit/engine-files.wxi
  msi/nunit/runner-directories.wxi
  msi/resources/nunit.agent.addins
  nuget/engine/nunit.agent.addins
  nuget/engine/nunit.engine.nuspec
  nuget/runners/nunit.agent.addins
  nuget/runners/nunit.console-runner.nuspec
  package-checks.cake
  src/NUnitEngine/nunit-agent/Program.cs
  src/NUnitEngine/nunit-agent/nunit-agent-x86.csproj
  src/NUnitEngine/nunit-agent/nunit-agent.csproj
  src/NUnitEngine/nunit.engine.tests/Integration/RunnerInDirectoryWithoutFramework.cs
  src/NUnitEngine/nunit.engine.tests/Services/RuntimeFrameworkServiceTests.cs
  src/NUnitEngine/nunit.engine/Services/TestAgency.cs
Labels: awaiting:contributor

#759 Use same current directory for agent as is being used by the runner
  src/NUnitEngine/nunit.engine.core/Internal/ServerBase.cs
  src/NUnitEngine/nunit.engine.tests/Integration/RemoteAgentTests.cs
  src/NUnitEngine/nunit.engine.tests/Services/AgentProcessTests.cs
  src/NUnitEngine/nunit.engine.tests/Services/AgentStoreTests.cs
  src/NUnitEngine/nunit.engine/Services/AgentProcess.cs
  src/NUnitEngine/nunit.engine/Services/AgentStore.cs
  src/NUnitEngine/nunit.engine/Services/TestAgency.cs
Labels: awaiting:review

#761 Revert accidental debug message change
  src/NUnitEngine/nunit.engine/Services/TestAgency.cs
Labels: awaiting:review

#769 Limit positive exit code to max of 100
  src/NUnitConsole/nunit3-console/ConsoleRunner.cs
Labels: awaiting:review

#777 Remove unused code to find engine from registry
  src/NUnitEngine/nunit.engine.api/TestEngineActivator.cs
Labels: is:refactor
