Repository nunit/nunit-console, pull requests merged in 2021-11, with the labels that each got.

#957 Include pdbs with nuget and zip packges and publish source code
  appveyor.yml
  build.cake
  nuget/engine/nunit.engine.api.nuspec
  nuget/engine/nunit.engine.nuspec
  nuget/runners/nunit.console-runner.nuspec
  package-checks.cake
  package-tests.cake
  src/NUnitEngine/nunit.engine.api/nunit.engine.api.csproj
  src/NUnitEngine/nunit.engine.core/nunit.engine.core.csproj
  src/NUnitEngine/nunit.engine/nunit.engine.csproj
Labels: awaiting:review

#956 fix for test assembly loading failure in NUnit.ConsoleRunner.NetCore
  src/NUnitEngine/nunit.engine.core/Drivers/NUnitNetCore31Driver.cs
  src/NUnitEngine/nunit.engine.core/Internal/CustomAssemblyLoadContext.cs
Labels: is:bug, pri:normal, awaiting:review

#1041 Consider later NUnit versions as a valid framework.
  src/NUnitEngine/nunit.engine.core/Drivers/NUnit3DriverFactory.cs
  src/NUnitEngine/nunit.engine.tests/Drivers/NUnit3DriverFactoryTests.cs
Labels: blocked, is:feature
