Repository nunit/nunit-console, pull requests merged in 2021-02, with the labels that each got.

#855 Improved testability of DirectoryFinder
  src/NUnitEngine/nunit.engine.core/Internal/DirectoryFinder.cs
  src/NUnitEngine/nunit.engine.core/Internal/FileSystemAccess/Default/Directory.cs
  src/NUnitEngine/nunit.engine.core/Internal/FileSystemAccess/Default/File.cs
  src/NUnitEngine/nunit.engine.core/Internal/FileSystemAccess/Default/FileSystem.cs
  src/NUnitEngine/nunit.engine.core/Internal/FileSystemAccess/IDirectory.cs
  src/NUnitEngine/nunit.engine.core/Internal/FileSystemAccess/IFile.cs
  src/NUnitEngine/nunit.engine.core/Internal/FileSystemAccess/IFileSystem.cs
  src/NUnitEngine/nunit.engine.core/Internal/IEnumerableExtensions.cs
  src/NUnitEngine/nunit.engine.core/Services/ExtensionService.cs
  src/NUnitEngine/nunit.engine.tests/Internal/DirectoryFinderTests.cs
  src/NUnitEngine/nunit.engine.tests/Internal/FileSystemAccess/Default/DirectoryTests.cs
  src/NUnitEngine/nunit.engine.tests/Internal/FileSystemAccess/Default/DirectoryTests2.cs
  src/NUnitEngine/nunit.engine.tests/Internal/FileSystemAccess/Default/FileSystemTests.cs
  src/NUnitEngine/nunit.engine.tests/Internal/FileSystemAccess/Default/FileTests.cs
  src/NUnitEngine/nunit.engine.tests/Services/ExtensionServiceTests.cs
Labels: awaiting:contributor

#895 Make sure `AssemblyDefinitions` are disposed after use.
  src/NUnitEngine/nunit.engine.core/Drivers/NUnitNetCore31Driver.cs
  src/NUnitEngine/nunit.engine.core/Drivers/NUnitNetStandardDriver.cs
  src/NUnitEngine/nunit.engine.core/Extensibility/ExtensionAssembly.cs
  src/NUnitEngine/nunit.engine.core/Services/DriverService.cs
  src/NUnitEngine/nunit.engine.core/Services/ExtensionService.cs
  src/NUnitEngine/nunit.engine/Services/RuntimeFrameworkService.cs
Labels: closed:done, is:bug

#902 Implement package tests
  NUnitConsole.sln
  NetFXTests.nunit
  build.cake
  package-checks.cake
  package-tests.cake
  src/NUnitEngine/mock-assembly/mock-assembly.csproj
  test-results.cake
Labels: awaiting:review

#906 Remove RecentFilesService from Engine
  src/NUnitEngine/nunit.engine.api/IRecentFiles.cs
  src/NUnitEngine/nunit.engine.tests/Services/RecentFilesTests.cs
  src/NUnitEngine/nunit.engine.tests/Services/ServiceDependencyTests.cs
  src/NUnitEngine/nunit.engine/Services/RecentFilesService.cs
  src/NUnitEngine/nunit.engine/TestEngine.cs
Labels: blocked
